<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Mongo</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>annotations</Nullable>
    <PackageId>Mongo</PackageId>
    <Authors>Devspace</Authors>
    <Company>Devspace</Company>
    <Description>Devspace Mongo</Description>
    <Copyright>@2026 - Devspace</Copyright>
    <RepositoryType>git</RepositoryType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.10.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
  </ItemGroup>

</Project>
